files:
  foods: "data/matvaretabellen_2026.csv"
  food_limits: "data/food_limits.csv"
  foods_extra: "data/matvaretabellen_extra.csv"
  nutrient_limits: "data/nutrient_limits.csv"
  energy_limits: "data/energy_limits.csv"
  custom_constraints: "data/custom_constraints.csv"

model:
  objective: "RI" # Options: "cost", "RI"
  write_lp_to_file: true
  lp_output_file: "output/model.lp"
  threshold: 0.0001
  energy_unit: "kJ" # Options: "kJ", "kcal"
  weight: 80 # weight in kg for weight-dependent requirements
  exclude_foodex2_groups:  # list of FoodEx2 groups to exclude from the optimization (e.g., "A03S")
    - "A03S"
    - "A038Q"
  exclude_categories:  # list of categories to exclude from the optimization
    - "Spedbarnsmat"
    - "Fisk og skalldyr"
    - "Meieriprodukter"
    - "Sukker og søte produkter"
    - "Drikke"
    - "Spisefett"
  solver: "HiGHS" # Options: "HiGHS", "CPLEX"

hard_coded_constraints:
  energy_intake: "2700 kcal" # energy intake (set to null to use input from csv-file) 
  food_item_limit: 0 # set to 0 for no limit, otherwise set to a positive integer
  lower_limit_unsalted_nuts: 20.0 # lower limit for unsalted nuts in grams (set to null for no limit)
  lower_limit_fruit_veg: 800.0 # lower limit for fruit and vegetables in grams (set to null for no limit)
  fruit_to_veg_ratio: null # ratio of fruit to vegetables (set to null for no ratio)
  lower_number_of_fruits: 2 # lower number of fruits (set to null for no limit)
  lower_number_of_vegetables: 2 # lower number of vegetables (set to null for no limit)

io:
  print_binding_only: false
  write_results_to_excel: true
  excel_output_file: "output/optimal_foods.xlsx"
  print_food_amounts: false
  print_energy_summary: true
  print_nutrient_summary: true
  print_scaled_foods: true
  print_constraints: true